from anthropic import Anthropic

from src.config.settings import ANTHROPIC_API_KEY
from src.tools.flight_status import (
    flight_status_lookup,
    flight_status_tool_schema,
)

client = Anthropic(api_key=ANTHROPIC_API_KEY)

user_question = "Is flight AI202 delayed?"


# Step 1: Send the question to Claude and provide the flight-status tool
response = client.messages.create(
    model="claude-sonnet-4-5",
    max_tokens=1024,
    tools=[flight_status_tool_schema],
    messages=[
        {
            "role": "user",
            "content": user_question,
        }
    ],
)


print("\n--- First response (Claude deciding what to do) ---")

for block in response.content:
    print(block)


# Step 2: Check whether Claude wants to use the tool
if response.stop_reason == "tool_use":

    tool_use_block = next(
        block for block in response.content if block.type == "tool_use"
    )

    # Step 3: Get the flight number generated by Claude
    flight_number = tool_use_block.input["flight_number"]

    # Step 4: Execute our real Python function
    tool_result = flight_status_lookup(flight_number)

    print("\n--- Tool executed locally ---")

    print(f"flight_status_lookup({flight_number}) " f"-> {tool_result}")

    # Step 5: Send the tool result back to Claude
    final_response = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=1024,
        tools=[flight_status_tool_schema],
        messages=[
            {
                "role": "user",
                "content": user_question,
            },
            {
                "role": "assistant",
                "content": response.content,
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "tool_result",
                        "tool_use_id": tool_use_block.id,
                        "content": str(tool_result),
                    }
                ],
            },
        ],
    )

    # Step 6: Print Claude's final natural-language response
    print("\n--- Final response (Claude answering in plain language) ---")

    for block in final_response.content:

        if block.type == "text":
            print(block.text)


else:

    print("\nClaude answered directly without needing the tool.")
